### ISSUE TITLE
Add `bold:` variant

### ISSUE THREAD

**Issue by kriomant** [cogciprocate/colorify#1]

**Comment by c0gent** [comment]
Most colors have a bold variant by appending `_bold` to the end (ex.: `yellow` -> `yellow_bold`).

See [http://doc.cogciprocate.com/colorify/colorify/macro.colorify!.html](http://doc.cogciprocate.com/colorify/colorify/macro.colorify!.html) or use: `colorify!(help);` for a full list.

**Comment by kriomant** [comment]
Yes, but how to get bold without any specific color (i.e. with default color)? And even if I have to specify some color, there is no "black" one in the list.

**Comment by c0gent** [comment]
I'll add black for you as soon as time permits. If I remember correctly, The ASCII code corresponding to black bold is grey or something and might already be in there. I'll have a look.

**Comment by c0gent** [comment]
25787115e09764fe916206cfe603971d96e20e9b
